baseurl = "//tyk.io/docs/4.3/"
languageCode = "en-gb"
title = "Tyk Documentation"
theme = "tykio"
MetaDataFormat = "yaml"
enableGitInfo = false
disableKinds = ["taxonomy", "taxonomyTerm"]
canonifyurls = "false"
timeout = "60s"
[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "manni"
    tabWidth = 2

  [markup.tableOfContents]
    startLevel = 3
    endLevel = 5
    ordered = true
[frontmatter]
lastmod = ["lastmod", ":git", "date", "publishDate"]

[outputFormats.urlcheck]
   mediaType = "application/json"
   baseName = "urlcheck"
   isPlainText = true
   notAlternative = true

[outputFormats.netlify]
  mediaType = "application/json"
  baseName = "netlify"
  isPlainText = true
  notAlternative = true
  
[imaging]
  anchor = 'Smart'
  bgColor = '#ffffff'
  hint = 'photo'
  quality = 100
  resampleFilter = 'Lanczos'

[outputs]
  home = ["HTML","netlify","urlcheck"]
